"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

palette = "catppuccin_mocha"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[os]
format = "[$symbol]($style) "
style = "blue"
disabled = false

[os.symbols]
EndeavourOS = " "

[character]
success_symbol = "[smol](mauve) ➤ "
error_symbol = "[smol](red) ✗ "

[username]
style_user = "bold mauve"
style_root = "bold red"
format = "[$user]($style) "
show_always = false

[directory]
style = "lavender"
format = "[$path]($style) "
truncation_length = 3
truncation_symbol = ".../"
truncate_to_repo = false

[directory.substitutions]
"Tiedostot" = " 󰈙 "
"Lataukset" = "  "
"Musiikki" = " 󰝚 "
"Kuvat" = "  "
"Repos" = "  "

[git_branch]
style = "peach"
symbol = " "
format = "[$symbol$branch]($style) "

[git_status]
style = "red"
format = "[($all_status$ahead_behind)]($style)"
ahead = "↑${count} "
behind = "↓${count} "
deleted = "✖${count} "
renamed = "➜${count} "
staged = "${count} "                           # nf-dev-git-staged
modified = "${count} "                         # nf-dev-git-modified
untracked = "${count} "                        # nf-dev-git-untracked
conflicted = "${count} "                       # nf-dev-git-conflict
